version: "3.7"
services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    ports:
      - '5000:5000'
    environment:
      MONGODB_DATABASE: flask_db
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: rootpassword
      MONGODB_HOSTNAME: mongodb
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      backend:
  mongodb:
    container_name: mongo-dev
    image: mongo
    hostname: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db
    networks:
      backend:
      frontend:
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
    ports:
      - '8081:8081'
    restart: always
    volumes:
      - mongodb_data_container:/data/db
    networks:
      frontend:



networks:
  backend:
    name: backend
  frontend:
    name: frontend
      

volumes:
  mongodb_data_container:


